openapi3/schema.go
These functions were assigning to a nil point as a result of not instantiating SchemaRef instances.
I was unable to run tests.  github.com/jban332/kin-test/jsontest requires github.com/jban332/kin-log which doesn't appear to exist.
=> Fixed New {OneOf,AnyOf,AllOf} Schema functions.

openapi3/content.go, openapi3/schema.go, openapi3/swagger_loader.go, openapi3filter/validate_request.go
- validate types supported in openapi 3.0
- handle cases where response content schema is empty
=>  conform type validation with openapi3

openapi3/swagger_loader.go, openapi3/swagger_loader_test.go
Howdie! Great project!
We're getting the following panic:
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x11e54af]
> 
> goroutine 21 [running]:
> testing.tRunner.func1(0xc4202801e0)
> 	/Users/.../go/src/testing/testing.go:742 +0x29d
> panic(0x17b9c00, 0x1d93d80)
> 	/Users/.../go/src/runtime/panic.go:502 +0x229
> .../vendor/github.com/getkin/kin-openapi/openapi3.(*SwaggerLoader).resolveSchemaRef(0xc420274840, 0xc420229e60, 0xc420316640, 0xc420390598, 0x0)
> 	.../vendor/github.com/getkin/kin-openapi/openapi3/swagger_loader.go:380 +0x16f
After reviewing swagger_loader.go, I noticed that all of the other …
=> add missing `nil` check in `resolveSchemaRef()`

openapi3/swagger_loader.go, openapi3/swagger_loader_test.go
This adds support for resolving [example references in media types](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#mediaTypeObject) when using the `examples` list. Here is a sample:
```yaml
components:
examples:
foo:
value:
msg: Hello, world!
paths:
/path:
get:
responses:
200:
application/json:
examples:
test:
$ref: "#/components/examples/foo"
```
Without this change you get back the raw ref when trying to output the example:
```js
{
"$ref": "#/components/examples/foo"
}
```
=> Resolve example references

openapi3/schema.go, openapi3/schema_test.go
I corrected the dateTime of format correctly because it is date-time.
ref. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types
=> Fix of format: date-time

openapi3filter/media_type.go, openapi3filter/validate_request.go, openapi3filter/validate_response.go
I also want to validate MediaType other than application/json as JSON.
- `application/json-patch+json`
- [RFC 6902 - JavaScript Object Notation (JSON) Patch](https://tools.ietf.org/html/rfc6902)
- `application/problem+json`
- [RFC 7807 - Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807)
Therefore, MediaType to be treated as JSON can be designated externally.
I am glad if you get input if there is any sense of incongruity in this IF.
=> Added MediaType definition to be interpreted as JSON

jsoninfo/unsupported_properties_error.go, openapi3/schema.go, openapi3/schema_test.go
I merged https://github.com/getkin/kin-openapi/pull/18 too fast and now I need to allow more formats than OpenAPIv3.0.1 explicitly allows. (e.g. [these](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-7)).
Note: additional schemas are not forbidden, from https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types
> Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.
@rikkkky I agree that strict validation is best. What do you think of this PR?
I'm starting to think that I should actually extend your code with the additional `format`s I want to support, since their validation will come eventually anyway. Thoughts?
Thanks
Yeah bear with me while I do that!
EDIT: done. Since it doesn't …
=> Un-strict validation of "format" in schemas

openapi3/operation.go, openapi3/operation_test.go
Fix a bug which will cause nil pointer panic. In the previous code in openapi3/operation:AddRespinse(), when operation.Responses == nil, any assignments to responses variable will panic as nil pointer since NewResponses() only assign to operation.Responses and remains responses to be nil.
=> fix: openapi3 operation AddResponse nil pointer

openapi3/swagger_loader.go, openapi3/swagger_loader_test.go
This adds a missing feature where path parameter references were ignored and the `param.Value` was  never filled in. Added a test which failed before but passes now.
=> Add support for path parameter refs

openapi3/swagger_loader.go, openapi3/swagger_loader_test.go
This PR fixes a bug related to loading references in request body examples. I'm running into this with one of our OpenAPI docs. Included test shows how to trigger the problem and that it's fixed by just copying the logic from the response function over to the request function.
=> Load request body examples ref

openapi3/security_scheme.go, openapi3/security_scheme_test.go
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securitySchemeObject
```
in: The location of the API key. Valid values are "query", "header" or "cookie".
```
=> Security scheme: adding in:cookie as an option

openapi3/discriminator.go, openapi3/schema.go
Here is a PR to handle the discriminator object rather than a string.
It would #25 
Love the library :)  I'm using it to do all sorts of swagger tests
=> feat(schema): add discriminator struct to match OpenAPI

openapi2/openapi2.go, openapi2conv/openapi2_conv_test.go
There was a typo in the json field name which prevented the parser from loading schemes properly.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields
=> Fix typo in swagger v2 schemes

openapi3/discriminator.go
Technically this is a backwardly incompatible change, but
the Discriminator type has not been officially released yet,
so it should be OK.
Fixes issue #60.
=> openapi3: use map[string]string for mapping

.gitignore, openapi3/swagger_loader.go, openapi3/swagger_loader_test.go, openapi3/swagger_test.go, openapi3/testdata/components.openapi.yml, openapi3/testdata/test.openapi.yml, openapi3/testdata/testref.openapi.yml
Enables YAML format support for specifications. Since JSON is a subset of YAML, we can just use the YAML parser to read both (thanks @fenollp).
I also removed `LoadSwaggerFromYAMLData` from `swagger_loader` as it does the same as `LoadSwaggerFromData` now and adjusted the tests accordingly.
=> Support loading specifications from YAML files

openapi3filter/validate_request.go, openapi3filter/validate_response.go
The previous behavior just said there was an unexpected value, but
didn't tell you what it was. Including the received value makes it
easier to debug and fix the actual discrepancy.
I also changed "Content-type" to "Content-Type" (uppercase T) in these
error messages to match the canonical form of the header.
=> Include value of unexpected Content-Type headers

openapi3/parameter.go, openapi3filter/param_decoder.go, openapi3filter/param_decoder_test.go, openapi3filter/validate_request.go
Proposed fix for issue #68.
I also implemented reading of a parameter's value according to a serialization method as it defined is the specification [(Describing parameters](https://swagger.io/docs/specification/describing-parameters/) and [Parameter serialization](https://swagger.io/docs/specification/serialization/))
=> Add support for keyword "explode" in an operation's parameter

openapi3/encoding.go, openapi3/encoding_test.go, openapi3/parameter.go, openapi3/serialization_method.go, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go, openapi3filter/validate_request.go, openapi3filter/validate_response.go
Hello. 
The PR adds support for decoding of request body with content types `"application/x-www-form-urlencoded"` and `"multipart/form-data"`. Also I add a decoder's implementation for files (see `openapi3filter.FileBodyDecoder`). 
The PR extends functional that appeared in [PR-78](getkin#78).
=> Decoding of request body with content types "application/x-www-form-urlencoded" and "multipart/form-data"

openapi3/schema_formats.go
`^[\\w]` in regexp does not make sense, as it reads literally as "not \ and not w". It causes any email that contains `w` character in the domain to fail validation. Example
```go
func main() {
payload := map[string]interface{}{
"prop1": "name@www.site.com",
}
schema := `{
"type": "object",
"required": ["prop1"],
"properties": {
"prop1": {
"type": "string",
"format": "email"
}
}
}
`
var dataSchema openapi3.Schema
json.Unmarshal([]byte(schema), &dataSchema)
err := dataSchema.VisitJSON(payload)
fmt.Println(err)
}
```
gives `Error at "/prop1":JSON string doesn't match the format 'email (regular expression ^[^@]+@[^@<>",\\w]+$)'`
My understanding, `\\w` should be `\s` which is "any whitespace"
=> fix email validation

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go, openapi3filter/validate_request.go, openapi3filter/validate_request_input.go, openapi3filter/validation_test.go
Fix crash in validation of parameters which are specified with
content rather than schema. The problem was that the presence
of a parameter with a nil schema in the Swagger spec would
crash the loop which validated over all parameters.
Added a callback to the request validation input so the user
can decode custom content types, and also implemented an
alternate code path for validation of content arguments. Added
an internal default parameter validator which is capable of
validating JSON encoded parameters.
=> Add content parameter validation

openapi3/content.go, openapi3/content_test.go, openapi3filter/validate_request.go, openapi3filter/validate_response.go
This implements the cascading wildcard behavior described in the OpenAPI
specification for request body and response body validation.
https://swagger.io/docs/specification/describing-request-body/
Closes #91
=> Add content-type wildcard support to validation

openapi3/content.go, openapi3/content_test.go
When a mime type is missing, rather than present and invalid, we return
the */* match as the request is not invalid for refusing to send a mime
type.
The RFC defining content-type states that including is a `SHOULD` rather than a `MUST`.
=> Support missing mime types in validation

openapi3/security_scheme.go, openapi3/security_scheme_test.go
The `bearerFormat` field in security schemas would only permit the values "JWT" and "", whereas the spec allows it to contain arbitrary strings. `bearerFormat` was also accepted for authentication types where it's
invalid, like "apiKey". Fixed the bug, modified one test and added another.
This fixes https://github.com/getkin/kin-openapi/issues/97.
=> Fix bug in bearerFormat validation

openapi2/openapi2.go
The default field is missing from parameter definition in V2
=> Added default option for Parameters

openapi3filter/validate_request.go, openapi3filter/validation_test.go
When no [security requirements are defined for an operation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-8), the [global security requirements](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields) need to be used according, which is what I implemented in the first commit.  
The second one modifies the way a security requirement is validated. Before, only the first scheme was validated, but according to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-8), all schemes must be valid for the request to be security requirement to be met.
=> Security requirements validation

openapi3filter/validate_request.go
While the Go docs make the guarantee that the request body for servers will always be non-nil, the same cannot be made for outgoing HTTP requests.
openapi3filter.ValidateRequest can be used to validate incoming requests as well as outgoing requests. While http.NoBody can be used in an outgoing client request to explicitly signal that a request has zero bytes, one can simply set Request.Body to nil. Under these circumstances, it is possible to encounter a nil pointer dereference. This PR amends the existing request body check to also check for nil.
=> add nil check in request body validation

openapi3/path_item.go, openapi3/swagger_loader.go, openapi3/swagger_loader_test.go, openapi3/testdata/circularref.openapi.yml, openapi3/testdata/pathref.openapi.yml
Hi! Thank you for the great library.
I'd like to use `$ref` in `paths` block.
I know we already have an opening pr for it https://github.com/getkin/kin-openapi/pull/73
But unfortunately it doesn't seem active with some change requests.
Then I tried to make another implementation.
I would be happy if this pr helps ones waiting for this feature :)
As you can see in the commit list, I made 3 changes;
1. Divided resolveComponent() into swagger part and component part
2. Supported `$ref` in `paths` block
3. Reset loader's internal state except from internal loading call
3rd change is needed, because in 2nd change, we need to have global state to avoid infinite recursion although we can use one SwaggerLoader for multiple loadings.
I also made a unit test case for this feature, and checked all …
=> $ref in paths block

openapi2/openapi2.go, openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go, openapi3/info.go, openapi3/operation.go, openapi3/operation_test.go, openapi3/server.go, openapi3/server_test.go, openapi3/swagger.go, openapi3/swagger_loader_test.go, openapi3/swagger_test.go, openapi3filter/req_resp_decoder_test.go, openapi3filter/router_test.go, openapi3filter/validation_test.go
Hello! I'm incorporating this library into an OpenAPI validation and management service and have noticed that the included validation functions don't check the `openapi` version object (i.e. it can be omitted and validation succeeds).
I've made the following changes in an attempt to address this:
- Adds validation to the `openapi` object
- Removes redundant validation on the `paths` object
- Annotates validation errors in nested objects
@nogates
=> Validate additional OpenAPI objects

openapi3/components.go, openapi3/discriminator.go, openapi3/encoding.go, openapi3/examples.go, openapi3/extension.go, openapi3/header.go, openapi3/info.go, openapi3/link.go, openapi3/media_type.go, openapi3/operation.go, openapi3/parameter.go, openapi3/path_item.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_scheme.go, openapi3/server.go, openapi3/swagger.go, openapi3/tag.go
This PR adds `yaml` tags to all exported struct attributes. This provides compatibility with alternate YAML parsers like [go-yaml/yaml](https://github.com/go-yaml/yaml).
=> Add YAML tags to all exported struct attributes

openapi3/schema.go
Fixing the schema error to state the value as the type passed in and in the reason state what the type should have been. Before this fix it was backwards which made reading the error confusing.
=> Update expectedType SchemaError message

README.md
`FindRoute` takes an `*url.URL` as parameter, not a string.
=> Fix GetOperation in README

openapi3/server.go, openapi3/server_test.go
Current `MatchRawUrl` implementation for an openapi3 `Server` attempts to skip the url input to either `.` or `/` characters when encountering a variable instead of continuing to match the expected template:
https://github.com/getkin/kin-openapi/blob/c856265a25d59d95e8fcb863d779da672c0ac489/openapi3/server.go#L79
This fails in instances where a user is trying to match prefixed or suffixed templates:
- `http://example.com/a/prefix-{arg3}-suffix`
or simply trying to match any variable with a `.` in the value:
- `http://example.com/a/1.0.0` does not match `http://example.com/a/{arg3}` but `http://example.com/a/1-0-0` does.
This fix replaces `.` with the next character in the pattern or `/` whichever comes first.
=> Fix server url matching

openapi3/header.go, openapi3/swagger_loader.go, openapi3/swagger_loader_relative_refs_test.go, openapi3/swagger_loader_test.go, openapi3/testdata/relativeDocs/CustomTestExample.yml, openapi3/testdata/relativeDocs/CustomTestHeader.yml, openapi3/testdata/relativeDocs/CustomTestParameter.yml, openapi3/testdata/relativeDocs/CustomTestPath.yml, openapi3/testdata/relativeDocs/CustomTestRequestBody.yml, openapi3/testdata/relativeDocs/CustomTestResponse.yml, openapi3/testdata/relativeDocs/CustomTestSchema.yml, openapi3/testdata/relativeDocs/CustomTestSecurityScheme.yml, openapi3/testdata/singleresponse.openapi.json, openapi3/testdata/singleresponse.openapi.yml, openapi3/testdata/testrefsinglecomponent.openapi.json, openapi3/testdata/testrefsinglecomponent.openapi.yml
This pull request builds on this [proof of concept](https://github.com/getkin/kin-openapi/pull/81) to give `kin-openapi` the feature to resolve relative documents for OpenAPI 3 specs.
It can resolve relative document references for:
- examples
- headers
- parameters
- request bodies
- responses
- schemas
- security schemes
- paths
and includes tests for all of these.
=> Resolve relative documents

openapi2/openapi2.go, openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
This makes it so the [v2 parameter default](https://swagger.io/docs/specification/2-0/describing-parameters/#default) is included as the [v3 parameter schema default](https://swagger.io/docs/specification/describing-parameters/#default).
Also includes a fix for serializing the v3 parameter schema max as a v2 parameter maximum.
Test change covers both.
=> Allow any type of default and serialize v3 parameter schema

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go, openapi3/components.go, openapi3/swagger.go
This moves tags in v3 from `components` to the root.  See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#openapi-object.
=> Tags at the root

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
The [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) requires that the full version identifier be used.
=> Use the full version specifier

openapi2/openapi2.go, openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
This rewrites refs to definitions and responses and includes those members when creating a v2 spec from a v3 spec.
Fixes #75.
=> Rewrite refs to definitions and responses

README.md
Thanks for this library! Vulcain uses kin-openapi especially for this part: https://github.com/dunglas/vulcain/blob/master/docs/gateway/openapi.md
=> Add Vulcain to the list of projects using kin-openapi

openapi3/header.go
Accordingly to the spec, the header object supports almost everything that is supported in the parameter object. Thus, I've added some of these attributes to the header (though I haven't added all. There are still some missing ones, like style, that might need a bit more work)
=> Add some missing attributes to header object

README.md, openapi3/schema.go, openapi3/schema_test.go, openapi3filter/validate_request.go, openapi3filter/validate_response.go
json.Unmarshal will store JSON object as map[string] interface{}
and store JSON array as []interface{}. Due to map and slice can
not be the key of map, so if the array items' type is JSON object
or JSON array, verify unique items of array will panic due map
and slice are unhashable.
=> Fix panic when verify array unique items(#143)

openapi3/parameter.go
From https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject
- A parameter MUST contain either a schema property, or a content property, but not both
=> Fixed missed case for parameter validation.

openapi3/swagger_loader.go, openapi3/swagger_loader_relative_refs_test.go, openapi3/testdata/relativeDocs/openapi/openapi.yml, openapi3/testdata/relativeDocs/openapi/responses/custom/CustomTestResponse.yml, openapi3/testdata/relativeDocsUseDocumentPath/CustomTestExample.yml, openapi3/testdata/relativeDocsUseDocumentPath/CustomTestHeader.yml, openapi3/testdata/relativeDocsUseDocumentPath/CustomTestParameter.yml, openapi3/testdata/relativeDocsUseDocumentPath/CustomTestRequestBody.yml, openapi3/testdata/relativeDocsUseDocumentPath/CustomTestResponse.yml, openapi3/testdata/relativeDocsUseDocumentPath/CustomTestSchema.yml, openapi3/testdata/relativeDocsUseDocumentPath/openapi/openapi.yml, openapi3/testdata/relativeDocsUseDocumentPath/openapi/paths/nesteddir/CustomTestPath.yml, openapi3/testdata/relativeDocsUseDocumentPath/openapi/paths/nesteddir/morenested/CustomTestPath.yml, openapi3/testdata/relativeDocsUseDocumentPath/openapi/responses/nesteddir/CustomTestResponse.yml
References should be resolved using the relative path of the referenced document.
According to the [Reference Object section](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#reference-object) in the OpenAPI 3.0.2 spec, reference resolution is accomplished as defined by the [JSON Reference specification](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html#RFC3986) which states:
> If the URI contained in the JSON Reference value is a relative URI, then the base URI resolution MUST be calculated according to [RFC3986], section 5.2. Resolution is performed relative to the referring document.
Instead of always using the root document’s directory when resolving refs, this PR correctly tracks the directory of each component as they are resolved.
=> Resolve references using the relative path of the referenced document

openapi3/external_docs.go
This PR modifies the `ExternalDocs` struct to support Extension Properties as defined in the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#external-documentation-object)
=> Add ExtensionProps field to ExternalDocs struct

openapi3/external_docs.go
My previous PR (https://github.com/getkin/kin-openapi/pull/163) added the `ExtensionProps` field to the `ExternalDocs` struct but forgot to include the strict marshal/unmarshal methods.
=> Add strict marshal/unmarshal to ExternalDocs

openapi3/operation.go, openapi3/schema.go
This PR adds the missing `ExternalDocs` field to the `Operation` type, and modifies the existing `ExternalDocs` field in the `Schema` type to use the correct type instead of `interface{}`
=> Add missing ExternalDocs to Operation, change ExternalDocs in Schema to use correct type

openapi2/openapi2.go, openapi3/path_item.go, openapi3filter/router_test.go
Use the `net/http` method constants to the operation methods.
Currently, hardcoded by a naive string type. But each method already provided from the `net/http` package.
Also, `Operations` are certainly http(s) access operations. I think using them is not wrong.
=> Use `net/http` method constants

openapi3/link.go
Change the type of `Link.Value.Headers` from `map[string]*Schema` to `map[string]*HeaderRef`
Fixes: https://github.com/getkin/kin-openapi/issues/188
=> fix: make link.Headers use HeaderRef

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
Validating a request body with content 'multipart/form-data' that contained parts not defined in the schema caused Panic, 
fixed by ignoring the undefined properties
=> fix panic when multipart form contains extra parts not present in schema

openapi3/schema.go
https://github.com/getkin/kin-openapi/issues/146#issuecomment-614729892
Adding a variable that allows the disabling of schema type format validation
=> Disable Format Validation Bool

openapi3/response.go
https://github.com/getkin/kin-openapi/issues/185
If the response description field was set empty string and passed into the LoadSwaggerFromData function, the field would be removed when sent due to the omitempty tag. This results in a definition that is invalid. 
Removing the omitempty tag on response description so the field is not dropped with a definition like below
```
{
"openapi": "3.0.0",
"info": {
"version": "1.0.0",
"title": "Sample API",
"description": "A sample API to illustrate OpenAPI concepts"
},
"paths": {
"/path1": {
"get": {
"responses": {
"200": {
"description": ""
}
}
}
}
}
}
```
I looked for other fields that might have similar issues but I could not find any
=> Remove omitempty from response description

openapi3filter/fixtures/petstore.json, openapi3filter/validation_error.go, openapi3filter/validation_error_encoder.go, openapi3filter/validation_error_test.go, openapi3filter/validation_handler.go, openapi3filter/validation_kit.go
Implement https://github.com/getkin/kin-openapi/issues/194 and https://github.com/getkin/kin-openapi/issues/195
This is what I had to add on top of kin-openapi in order to provide openapi validation errors in my API service. More discussion at https://github.com/getkin/kin-openapi/issues/194#issuecomment-605488953
=> Add validation handler and error encoder

README.md
This links to [Restish](https://rest.sh/) in the README. The project supports OpenAPI out of the box via `kin-openapi`.
=> feat: add Restish to README

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
`ToV3Swagger` func should include `ExternalDocs` prop. Without this, it is required to set it explicitly, e.g.:
```
v3, err := openapi2conv.ToV3Swagger(&v2)		
v3.ExternalDocs = v2.ExternalDocs
```
=> openapi2_conv: include ExternalDocs prop when converting to v3

openapi3/swagger_loader.go
Added a support for absolute paths in external references. 
Before, everything was interpreted as relative paths.
```$ref: /hello/world/spec.json#/components/schemas/HelloWorld``` - this is the absolute path, not the relative
=> added a support for absolute paths in $ref

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go, openapi3/content.go, openapi3/request_body.go
This change enables converting spec for file upload with POST from v2 to v3 and vice versa
according to https://swagger.io/docs/specification/2-0/file-upload/ specification.
Added support for `multipart/form-data`.
Added `in: formData` case for file upload.
Updated unit tests related sections.
=> conversion: conversion for file upload from v2 to v3 and vice versa

openapi2conv/issue187_test.go, openapi2conv/openapi2_conv.go, openapi3/components.go
=> Fix wrong `Found unresolved ref` error when converting from Swagger/OpenAPIv2 spec

openapi3/schema.go
Change-Id: If750ff340ae29cf24a6ad870071502c9327485ca
As the spec described, there is a deprecated field in schema.
https://swagger.io/docs/specification/data-models/keywords/
=> Add deprecated field in Schema

openapi3/swagger_loader.go, openapi3/swagger_loader_referenced_document_path_test.go
`openapi3.referencedDocument` tried to `path.Join` two URLs, and then
generate a new `url.URL` by parsing the obtained path. The URL
obtained at the end would be invalid, when the base path is HTTP URL.
Given base path as 'http://example.com/schemas' and ref as '/schema1',
the obtained end URL would be 'http:/example.com/schemas'. This happens
because `path.Join` cleans the path it generates and replaces repeated
'//' with a single '/'.
This is fixed by doing a `path.Join` on the base URL.Path and the ref,
and setting this result as the URL.Path of the new URL.
=> Fix openapi3.referencedDocumentPath

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
Issue: 
FormData and standard request bodies defined at root level in a swagger 2 definition would fail the conversion as references could not be resolved as they aren't converted correctly.
V2ToV3 changes
- Changed Parameters `in: formData` to convert to schema refs rather than a request body at levels other than the operation level (because it made it easier to be used in references)
- When converting refs, appropriate conversion from `parameters/` to `components/parameters`, `components/requestBodies` or `components/schemas`
- Added `x-formData-name` and `x-originalName` to the conversions for testing purposes (mostly) so that the original names for parameters are used (e.g. the parameter name which is usually lost on conversion at that level).
V3ToV2 changes
- Converting root level …
=> swagger2 formData & request body refs

openapi3filter/fixtures/petstore.json, openapi3filter/validation_error_encoder.go, openapi3filter/validation_error_test.go
The Parameter can be nil when the enum is set of one of the body fields.
=> Prevent a panic in the error encoder

openapi3/schema.go, openapi3/schema_formats.go, openapi3/schema_test.go
=> Adds ipv4 and ipv6 formats support

openapi3/doc.go
Fix broken link in `openapi3/doc.go`
=> Fix broken link in openapi3/doc.go

openapi3/security_scheme.go, openapi3/security_scheme_test.go
https://swagger.io/docs/specification/authentication/openid-connect-discovery/
=> Add OIDC Schema format as per spec

openapi3/security_scheme.go, openapi3/security_scheme_test.go
Fixes #290
Support for negotiate and digest auth schemes that are in common use.
=> Support for alternate http auth mechanisms

openapi3/schema.go, openapi3/schema_issue289_test.go
=> Return a more specific error when more than oneOf schemas match

openapi2/openapi2.go, openapi3/server.go, openapi3/tag.go
Regarding https://github.com/getkin/kin-openapi/issues/299 still having some resources mismatching the documentation.
Adding them 🙂
=> Add extensions in missing resources

openapi3/swagger_loader.go, openapi3/swagger_loader_recursive_ref_test.go, openapi3/testdata/recursiveRef/components/Bar.yml, openapi3/testdata/recursiveRef/components/Foo.yml, openapi3/testdata/recursiveRef/openapi.yml, openapi3/testdata/recursiveRef/paths/foo.yml
Try to fix https://github.com/getkin/kin-openapi/issues/309
=> Prevent infinite loop while loading openapi spec with recursive references

jsoninfo/field_info.go, openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go, openapi3gen/simple_test.go
=> Add an openapi3gen example + options

openapi3/schema.go
Updating schema.Pattern should reset schema.compiledPattern so that the next validation will use the new value.
See https://github.com/getkin/kin-openapi/blob/3690b664fe9e5aa8e7e5de77833da7c32d08b6fa/openapi3/schema.go#L1141
=> Reset compiledPattern when updating Pattern

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
Fixes https://github.com/getkin/kin-openapi/issues/339
=> introduce openapi3filter.RegisteredBodyDecoder

openapi3/server.go, openapi3/swagger_loader_test.go, routers/gorillamux/router.go, routers/gorillamux/router_test.go, routers/legacy/router_test.go
=> openapi3: allow variables in schemes in gorillamux router + better server variables validation

openapi3/swagger_loader_outside_refs_test.go, openapi3/testdata/303bis/common/properties.yaml, openapi3/testdata/303bis/service.yaml
cc https://github.com/getkin/kin-openapi/issues/303#issuecomment-786521697
cc @Integralist
=> reproduce failing to load JSON refs in non-openapi document

openapi3/swagger_loader.go, openapi3/swagger_loader_http_error_test.go
@fenollp you were right: The error should include the location. The problem is, that the handling is different if the reference is just a file without a reference (\#....). I added a test case for that and aligned the error message.
=> [Bugfix] fixed error message when only file is referenced

openapi3filter/testdata/petstore.yaml, openapi3filter/unpack_errors_test.go, routers/legacy/validate_request_test.go
Thanks to https://github.com/getkin/kin-openapi/pull/259#issuecomment-832813819
=> add example usage of request validation with gorilla/mux router

openapi3/header.go, openapi3/openapi3_test.go, openapi3/parameter.go
Fixes #46
@pruser @danielvladco can you confirm this meets your needs? I'm asking specifically about the awkward way to construct a `Header.Value`:
```go
Headers: map[string]*HeaderRef{
"someHeader": {
Ref: "#/components/headers/otherHeader",
},
"otherHeader": {
Value: &Header{Parameter{Schema: &SchemaRef{Value: NewStringSchema()}}},
},
},
```
=> Have Header Object follow the structure of the Parameter Object

openapi3/issue376_test.go, openapi3/loader.go, openapi3/schema.go
=> fix drilling down struct looking for additionalProperties

openapi3/issue382_test.go, openapi3/parameter_issue223_test.go, openapi3/paths.go, openapi3/testdata/Test_param_override.yml
=> reproduce and fix issue #382

jsoninfo/field_info.go, openapi3gen/openapi3gen_test.go
This PR adds a guard clause so that if an embedded struct is an embedded struct _pointer_, `field_info.AppendFields` will set `t` to the underlying element. 
- Unit test added
- All tests passing
=> Add support for embedded struct pointers

routers/gorillamux/router.go, routers/gorillamux/router_test.go
=> fix: Allow encoded path parameters with slashes

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
handle non-file parts of `multipart/form-data` as `text/plain`. ref https://github.com/getkin/kin-openapi/issues/398
=> Accept multipart/form-data's part without Content-Type

openapi3/loader.go, openapi3/loader_read_from_uri_func_test.go, openapi3/loader_recursive_ref_test.go, openapi3/testdata/load_with_go_embed_test.go, openapi3/testdata/recursiveRef/components/Foo.yml, openapi3/testdata/recursiveRef/components/Foo/Foo2.yml, openapi3/testdata/recursiveRef/openapi.yml, openapi3/testdata/recursiveRef/paths/foo.yml
=> Fix handling recursive refs

openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go
We would like to support additional descriptions and metadata field-by-field in our project.
Specific examples:
- Adding translated field-level descriptions
- Documenting possible values for an enum field
- Custom min/max values
This PR proposes a minimal change to the `openapi3gen` codebase, to allow projects like ours to have their own extensions using custom struct tags to annotate the Go structs with this extra information.
=> Schema customization plug-point

README.md
Remove https://github.com/getkin/kin from the list of dependable projects because it's empty repo.
=> Update README: remove github.com/getkin/kin

go.mod, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
Yaml follows the same flow as json, but with a different unmarshaller.
Added both Contet-Types:
- `application/yaml`
- `application/x-yaml`
Unsure if `text/yaml` should also be added
Reused currently yaml.v2 used by the project
=> Add support for "application/x-yaml"

openapi3/schema_formats.go, openapi3/schema_formats_test.go
=> sort out possible mishandling of ipv4 vs v6

openapi3/internalize_refs.go, openapi3/internalize_refs_test.go
I needed this functionality for some tooling I'm building and thought I would make a pull request in-case anyone would find it useful. If so I can create a few tests too.
All this does is either inline or add to the components section all external references, so that when you write the file back out it is self contained and portable. This makes it easier for other tools to process and removes all dependencies.
If there's a better way of doing this let me know and I will update my code!
=> Internalize references

openapi2conv/issue187_test.go, openapi2conv/openapi2_conv.go
ClientCredentials was called application in OpenAPI v2 so this needs to be converted.
Specification:
https://swagger.io/specification/#oauth-flows-object
=> ClientCredentials conversion to OpenAPI v2

README.md, openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go, openapi3gen/simple_test.go
Superseeds https://github.com/getkin/kin-openapi/pull/451
=> Provide support for generating recursive types into OpenAPI doc #451 + my touches

openapi3filter/middleware.go, openapi3filter/middleware_test.go
This change introduces middleware which wraps an `http.Handler` with OpenAPI 3 request and response validation.
In developing this middleware, I thought it would benefit others trying to do the same. This is my first time contributing here, happy to answer any questions and discuss further.
Thank you for such an awesome OpenAPI library by the way!
=> Add openapi3 validator middleware

routers/gorillamux/router.go, routers/gorillamux/router_test.go
The existing path sorting approach is flawed, because calls to `Router.FindRoute()` invariably lead to `routers.ErrMethodNotAllowed` where both `/{X}` and `/{X}:<someSuffix>` are present.  This occurs because `gorillamux` does not preclude `:` inside parameter substitutions and the shorter templated path is evaluated first.  The suggested fix is simply to reverse the lexicographical ordering.  Thus, the longer path is evaluated first.
The prior unit tests leverage lexicographical sorting on the parameter name itself, coupled with opportune parameter name selection, to ensure passing tests.  However, according to https://swagger.io/specification/#patterned-fields:
> Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical.
This is also …
=> extensible-paths

openapi2/openapi2.go, openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
v2 <-> v3 conversion of the Response.Headers objects
=> openapi2conv: Convert response headers

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
This change fixes an issue in `openapi2conv.fromV3RequestBodies` where it didn't distinguish a "formData" parameter from a "body" parameter.
Given the following spec:
```json
{
"info": {
"description": "Test Spec",
"title": "Test Spec",
"version": "0.0.0"
},
"components": {
"requestBodies": {
"FooBody": {
"content": {
"application/json": {
"schema": {
"properties": { "message": { "type": "string" } },
"type": "object"
}
}
},
"description": "test spec request body.",
"required": true
}
}
},
"paths": {
"/foo-path": {
"post": {
"requestBody": { "$ref": "#/components/requestBodies/FooBody" },
"responses": { "202": { "description": "Test spec post." } },
"summary": "Test spec path"
}
}
},
"servers": [{ "url": "http://localhost/" }],
"openapi": "3.0.3"
}
```
Would produce the following output: …
=> distinguish form data in fromV3RequestBodies

openapi3/loader.go, openapi3/loader_uri_reader.go
This introduces simple URI-based caching.
A basic map-based cache implementation is provided, which may cover many
simple use cases. This caching is now used by default in the Loader.
File and HTTP URI readers are extracted from the loader internals so
that they may be extended, replaced, or configured. ReadFromHTTP allows
specifying the http.Client used to read HTTP $refs, for example.
Supersedes #117 and fixes #334.
=> feat: cache resolved refs, improve URI reader extensibility

openapi3/openapi3_test.go, openapi3/request_body.go
According to [request body object  spec section](https://spec.openapis.org/oas/v3.0.3#request-body-object) content field is required. Seems like it would be better to validate this.
P.S.: we use this cool library for strict OpenAPI v3 specs validation in one of our project, that's why I dive into this:)
=> Fix OpenAPI 3 validation: request body content is required

openapi3/paths.go, openapi3/paths_test.go, openapi3filter/fixtures/petstore.json
Hi,
According to the [OpenAPI 3 spec](https://spec.openapis.org/oas/v3.0.3#operation-object) `operationId` must be unique among all operations described in the API. Suggest adding validation for this.
If all is ok, could you please release a new module version (v0.91.0)?
=> Fix OpenAPI 3 validation: operationId must be unique

.github/workflows/go.yml, .gitignore, go.mod, openapi3/external_docs.go, openapi3/load_with_go_embed_test.go, openapi3/request_body.go
Since https://github.com/deepmap/oapi-codegen/pull/322#issuecomment-805192283 the project has moved on from go1.14
=> fix that test situation

openapi3/schema.go, openapi3/schema_oneOf_test.go
With out this check, the request with body like `{"discriminator": null}` or `{"discriminator": 1}` will simply get panic 
```
interface conversion: interface {} is nil, not string
```
=> discriminator value should verify the type is string to avoid panic

.github/workflows/go.yml, openapi3/schema.go
Fixes https://github.com/getkin/kin-openapi/issues/507
=> Add nilness check to CI

openapi3filter/validate_request.go, openapi3filter/validate_request_test.go
The security schemas are being checked after all other parameters are checked, this could possibly give a user who is not authorised to see validation errors that expose how the request works, instead of giving them an error that they are not authorised.
- Moved the security check to be before all the other parameters
- Added tests for ValidateRequest to show that this solution fixes the issue
- Fixes https://github.com/getkin/kin-openapi/issues/416
=> Change the order of request validation to validate the Security schemas first before all other paramters

openapi3filter/middleware_test.go
Fix an integer overflow in ExampleValidator on 32-bit architectures (where `65536 * 65536` with `int` returns `0`)
by using int64 for square calculations.
Tested with `GOARCH=386 go test ./...`
See Debian Bug report log "autopkgtest regression on armhf and i386" at https://bugs.debian.org/1007733
Many thanks!
=> Fix ExampleValidator test for 32-bit architectures

openapi2/openapi2.go
closes https://github.com/getkin/kin-openapi/issues/366
=> openapi2: add missing schemes field of operation object

openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go
This PR extends the functionality of the schemaCustomizer to allow the customizer to indicate that the schema for a specific field should actually be ignored in the final schema output.
This is useful for cases where might be building a schema for a struct that has internal fields which should not be exposed in the generated Open API spec. It can also be useful in cases where the Go code uses a single struct as input and output JSON, but some fields (say an `id` for example) are only present on the HTTP response, and should not be part of the schema for a request.
Using a sentinel error seemed to be the least intrusive change to the code to enable this, and also still maintain backwards compatibility by not changing the function signature, but I'm open to feedback.
=> Add ExcludeSchema sentinel error for schemaCustomizer

openapi2/openapi2.go, openapi3/callback.go, openapi3/components.go, openapi3/content.go, openapi3/discriminator.go, openapi3/encoding.go, openapi3/example.go, openapi3/external_docs.go, openapi3/header.go, openapi3/info.go, openapi3/link.go, openapi3/media_type.go, openapi3/openapi3.go, openapi3/operation.go, openapi3/parameter.go, openapi3/path_item.go, openapi3/paths.go, openapi3/refs.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_requirements.go, openapi3/security_scheme.go, openapi3/server.go, openapi3/tag.go, openapi3/xml.go
=> Fix some golints

openapi3/internalize_refs.go, openapi3/testdata/recursiveRef/parameters/number.yml, openapi3/testdata/recursiveRef/paths/foo.yml
We use externalized parameters in our OpenAPI spec. While running `InternalizeSpec` those were not internalized. This is a fix for that bug.
=> Internalize parameter references in the path as well

openapi3filter/req_resp_decoder.go, openapi3filter/validation_error_test.go
This is the original error we get when parsing an invalid boolean value. E.g. `2`
```
request is not valid JSON: value 2: an invalid number: strconv.ParseBool: parsing \"2\": invalid syntax
```
So this fix two things. 
1. it should be `an invalid boolean` instead of `an invalid number`
2. `strconv.ParseBool` exposes our Go implementation and `parsing \"2\"` seems redundant, so we remove this
=> fix bad error message on invalid value parse on query parameter

openapi2conv/issue573_test.go, openapi2conv/openapi2_conv.go
Closes #573 
---
`ToV3Response` now accepts the content of the "produces" field and creates the responses with the right content-type.
=> fix: openapi2conv respects produces field

jsoninfo/marshal.go, jsoninfo/marshal_test.go, jsoninfo/unmarshal.go, openapi3/errors.go, openapi3/internalize_refs.go, openapi3/paths.go, routers/legacy/pathpattern/node.go
=> Use go1.19 formatting

openapi3/load_cicular_ref_with_external_file_test.go, openapi3/loader.go, openapi3/testdata/circularRef/base.yml, openapi3/testdata/circularRef/other.yml
I can't find contribution guidelines. If you know it, would you let me know it?
At the following case, `resolveSchemaRef()` fails to load other spec. files.
* A schema participate a circular reference.
* The schema has references to component's schema in external spec. files.
* Add test case: `TestLoadCircularRefFromFile`
* Change `resolveSchemaRef()` to fix it.
`resolveSchemaRef()` miss file path's information during recursive resolving schema reference.
For describe, I'm going use following example.
```directory tree
./testdata
|- a.yml
|- b.yml
```
```a.yml
components:
schemas:
Foo:
properties:
bar:
$ref: "#/components/schemas/Bar"
foo2:
$ref: "b.yml#/components/schemas/Foo"
Bar:
properties:
foo:
$ref: "#/components/schemas/Foo"
```
```b.yml
components:
schemas:
Foo:
properties:
id: …
```
=> Fix `resolveSchemaRef()` to load correctly an other spec. file referenced by `$ref`

openapi3/internalize_refs.go, openapi3/openapi3.go, openapi3/testdata/recursiveRef/components/Cat.yml, openapi3/testdata/recursiveRef/openapi.yml, openapi3/testdata/recursiveRef/openapi.yml.internalized.yml, openapi3/visited.go
Fixes stack overflow panic when schema includes link to itself, like:
```
components:
schemas:
Item:
type: object
properties:
Name:
type: string
ParentLink:
$ref: '#/components/schemas/Item'
```
=> Protect from recursion in openapi3.InternaliseRefs

openapi3/schema.go, openapi3/schema_test.go
This PR aims at closing issue #482. 
I also added support for int32/64 integer formats during data validation.
=> #482 integer support broken with yaml

routers/gorillamux/router.go, routers/gorillamux/router_test.go
This adds support for overriding servers at the path level.
Support for overriding servers at the operation level is still not supported.
=> Match on overridden servers at the path level, fixes #564

jsoninfo/unmarshal.go, openapi3/components.go, openapi3/header.go, openapi3/loader.go, openapi3/loader_test.go, openapi3/media_type.go, openapi3/openapi3.go, openapi3/parameter.go, openapi3/schema.go, openapi3/schema_formats.go, openapi3/security_scheme.go, openapi3filter/req_resp_decoder.go, routers/legacy/router.go
Update all usage of the `fmt.Errorf` to use `%w` instead of `%s` or `%v` for the wrapped errors
=> use %w to wrap the errors

openapi3filter/middleware.go, openapi3filter/middleware_test.go
Added new ValidatorOptions funtion to pass the validation options.
The context is that while ValidateRequest and ValidateResponse have configurable Options exposed through their input objects, the same Options cannot be passed when using the middleware/Validator approach.
The usecase that triggered the change was the validation of a response status code that is not in the API spec. ValidateResponse would check for it if the right option was passed, but there was no way to do it through the Validator.
=> Expose request/response validation options in the middleware Validator

openapi3/issue136_test.go, openapi3/schema.go
Closes https://github.com/getkin/kin-openapi/issues/136
=> Validate default values against schema

openapi3/example_validation_test.go, openapi3/loader_test.go, openapi3/path_item.go, openapi3/paths.go, openapi3/response_issue224_test.go
With the introduction of validation of examples in an OpenAPI spec in #592 there is now a high chance that many will have specs that fail validation. I did! It was hard to debug what was wrong with the spec as the errors were too generic. The change in this PR will hopefully make it easier for folks to debug the problem in their OpenAPI docs.
=> Improve error message when path validation fails

openapi3/internalize_refs_test.go, openapi3/loader.go, openapi3/loader_recursive_ref_test.go, openapi3/testdata/recursiveRef/components/models/error.yaml, openapi3/testdata/recursiveRef/openapi.yml, openapi3/testdata/recursiveRef/openapi.yml.internalized.yml, openapi3/testdata/recursiveRef/paths/foo.yml
Where previously following path was resolved `testdata/components/models/error.yaml`, missing `recursiveRef` folder.
=> Correctly resolve path of yaml resource if double referenced.

openapi3/errors.go, openapi3filter/testdata/petstore.yaml, openapi3filter/unpack_errors_test.go
Fixes https://github.com/getkin/kin-openapi/issues/589
=> rework convertError Example code to show query schema error

routers/issue356_test.go, routers/legacy/router.go, routers/legacy/router_test.go
My proposal to implement https://github.com/getkin/kin-openapi/issues/613
=> Allow validations options when creating legace Router

openapi3/components.go, openapi3/example.go, openapi3/example_validation_test.go, openapi3/issue601_test.go, openapi3/media_type.go, openapi3/parameter.go, openapi3/schema.go
An attempt to provide clearer paths for validation errors
=> Additional error information

jsoninfo/field_info.go, openapi3gen/openapi3gen_test.go
Embedded structs with a json tag name are not nested as would be expected. This fixes this.
=> fix: embedded struct handling

README.md, openapi3/loader.go, openapi3filter/issue624_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/validate_request.go
=> openapi3filter: Fallback to string when decoding request parameters

openapi3filter/issue624_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/validate_request.go, openapi3filter/validation_test.go
cc https://github.com/getkin/kin-openapi/issues/632
=> Actually  #624, thanks to @orensolo

.gitattributes, openapi3/components.go, openapi3/discriminator.go, openapi3/encoding.go, openapi3/example.go, openapi3/external_docs.go, openapi3/info.go, openapi3/issue241_test.go, openapi3/link.go, openapi3/media_type.go, openapi3/openapi3.go, openapi3/operation.go, openapi3/parameter.go, openapi3/path_item.go, openapi3/refs.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_scheme.go, openapi3/server.go, openapi3/tag.go, openapi3/testdata/issue241.yml, openapi3/xml.go
Fix the output when encoding the YAML by:
* Excluding ExtensionProps, the Extensions were already excluded resulting in empty extensionProps only.
* Add custom marshaler to all ref types so it doesn't output both values in the same way the JSON marshaler does.
Fixes #241
=> fix: yaml marshal output

openapi3/errors.go, openapi3/issue657_test.go, openapi3/schema.go
Now we can get error types when using oneOf #657
=> Fix lost error types in oneOf

openapi3/issue652_test.go, openapi3/loader.go, openapi3/testdata/issue652/definitions.yml, openapi3/testdata/issue652/nested/schema.yml
Fixes panic from the issue #652, that occurs when trying to load specification from file that contains reference to the file insed of parent directory.
=> fix panic slice out of range error #652

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
Adds support for the `x-nullable` convention for OpenAPI V2 conversion. Since nullable fields are not supported in the v2 spec a convention was been adopted of adding a `x-nullable: true` attribute to properties.
This PR adds support for setting the `nullable` attribute for V2 > V3 conversion which does support nullable fields and vice-versa.
=> Support x-nullable

openapi3filter/validate_request.go, openapi3filter/validate_request_test.go
Update content length after replacing the request body when setting default values. Otherwise, the request gets inconsistent, and further operation on it, like proxying it, causes an error.
=> Update content length after replacing request body

openapi3filter/issue639_test.go, openapi3filter/options.go, openapi3filter/validate_request.go
Adding the option to skip setting default values in the request body after validation.
See https://github.com/getkin/kin-openapi/issues/639
=> fix: optional defaults

openapi3/issue136_test.go, openapi3/schema.go, openapi3filter/issue201_test.go, openapi3filter/issue625_test.go, openapi3filter/unpack_errors_test.go, openapi3filter/validation_error_test.go, routers/gorillamux/example_test.go
This commits adds some clarity to the end users about what it is failing on their end, adding values does not match, value X is not part of the enum, etc.. So for end-users, it's a bit easier to understand.
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>
=> feat: formatting some error messages

openapi3filter/issue641_test.go, openapi3filter/req_resp_decoder.go
This pull request fixes issue https://github.com/getkin/kin-openapi/issues/641
=> fix: query param pattern

openapi3/schema.go, openapi3/schema_oneOf_test.go
=> fix: errors in oneOf not contain path (#676)

openapi3/internalize_refs.go, openapi3/issue618_test.go, openapi3/testdata/schema618.yml
Addressing issue #618 by tracking if parents are externally referenced through the recursion tree. 
Tests are passing along with repro posted in #635
=> Internalize recursive external references #618

openapi3/schema.go, openapi3filter/validate_set_default_test.go
When setting default values for oneOf or anyOf, a temporary value (tempValue) is used to prevent original value from being modified. However, tempValue should to be reset on the next iteration otherwise default value set from previous iteration can modify tempValue which can lead to failure.
The fix is to move the deepcopy inside the loop, which will reset tempValue to the original input.
=> fix: setting defaults for oneOf and anyOf

.github/workflows/go.yml, openapi3/loader.go
Fixes https://github.com/getkin/kin-openapi/issues/680
=> Try decoding as JSON first then YAML, for speed

openapi3filter/validate_request.go, openapi3filter/validate_request_test.go
Fix for https://github.com/getkin/kin-openapi/issues/703.
=> Use and update GetBody() member of request

openapi3filter/issue625_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
parse integer primitives as int32 or int64, rather than float64
=> openapi3filter: parse integers with strconv.ParseInt instead of ParseFloat

openapi3/callback.go, openapi3/components.go, openapi3/discriminator.go, openapi3/doc.go, openapi3/encoding.go, openapi3/example.go, openapi3/header.go, openapi3/info.go, openapi3/link.go, openapi3/media_type.go, openapi3/openapi3.go, openapi3/parameter.go, openapi3/path_item.go, openapi3/refs.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_requirements.go, openapi3/security_scheme.go, openapi3/security_scheme_test.go, openapi3/server.go, openapi3/tag.go, openapi3/xml.go
=> Fix links to OpenAPI spec after GitHub changes

jsoninfo/marshal.go, openapi2/openapi2.go, openapi2conv/openapi2_conv.go, openapi3/content.go, openapi3/path_item.go, routers/legacy/router.go
=> Leave allocation capacity guessing to the runtime

.github/workflows/go.yml, openapi2/openapi2.go, openapi2conv/openapi2_conv.go, openapi3/internalize_refs.go, openapi3/loader.go, openapi3/openapi3.go, openapi3/paths.go, routers/gorillamux/router.go
=> openapi3: introduce (Paths).InMatchingOrder() paths iterator

openapi3/schema.go, openapi3/schema_oneOf_test.go
First, the error messages themselves are better: they give the name of the discriminator property itself, which gives the reader a clue where the problem lies. And they give the invalid value when there is one.
Second, using SchemaError rather than errors.New() makes it possible for downstream interpreters to add more value to the error.
=> feat: improve error reporting for bad/missing discriminator

openapi3filter/issue707_test.go, openapi3filter/validate_request.go
this pull request solves https://github.com/getkin/kin-openapi/issues/707 issue
=> openapi3filter: use option to skip setting defaults on validation

README.md, openapi3/schema_formats.go
addresses https://github.com/getkin/kin-openapi/issues/724 follow-up
=> openapi3: remove email string format

openapi3filter/issue722_test.go, openapi3filter/req_resp_decoder.go
fix #722
No support for anyOf schema is provided.
=> openapi3filter: support for allOf request schema in multipart/form-data

.github/docs/openapi3filter.txt, openapi3filter/csv_file_upload_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
=> openapi3filter: RegisterBodyDecoder for text/csv

.github/workflows/go.yml, openapi3/issue741_test.go, openapi3/loader_uri_reader.go
Adds mutex around uri ref cache.
=> #741 uri cache mutex

openapi3/security_scheme.go
Encountered this while trying to validate a schema with "oauth2" type for security scheme.
=> openapi3: fix error phrase in security scheme

openapi3/issue746_test.go, openapi3/schema.go
Resolves #746
The issue was with `Schema.IsEmpty()` assuming incorrectly that `additionalProperties=false` means empty schema while the default value for `additionalProperties` is `true`.
From the [spec](https://spec.openapis.org/oas/v3.0.3#properties):
> `additionalProperties` - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, **`additionalProperties` defaults to `true`**.
=> Fix additional properties false not validated

openapi3/issue136_test.go, openapi3/issue735_test.go, openapi3/schema.go, openapi3/schema_oneOf_test.go, openapi3filter/issue641_test.go, openapi3filter/unpack_errors_test.go, openapi3filter/validation_error_test.go, routers/gorillamux/example_test.go
This PR adds tests to the behavior that was added in #735.
The purpose of the tests is to verify that the validated value doesn't appear in the `SchemaError.Reason` field.
Additionally, this PR refines the messages in `SchemaError.Reason` and makes sure `Reason` is always set.
=> Refine schema error reason message

openapi3/schema.go, openapi3/schema_test.go
Resolves #751 
In `VisitJSON` after the `switch` block, it checks `value`'s Kind. If it is a Slice, it transforms the `value` into a slice of empty interfaces and passes it to `visitJSONArray`
`TestSchemas` did not catch this because the data (`AllValid` and `AllInvalid`) are coerced to empty interface types.
=> openapi3: fix validation of non-empty interface slice value against array schema

openapi3/security_scheme.go, openapi3/security_scheme_test.go
accoriding to v3.1.0 documentation the scopes field can be empty.
https://spec.openapis.org/oas/v3.1.0#fixed-fields-24
=> openapi3: empty scopes are valid

.github/docs/openapi3.txt, openapi3/issue689_test.go, openapi3/schema.go, openapi3/schema_validation_settings.go, openapi3filter/issue689_test.go, openapi3filter/options.go, openapi3filter/validate_request.go, openapi3filter/validate_response.go
=> optional readOnly and writeOnly validations

openapi3/internalize_refs.go, openapi3/issue341_test.go, openapi3/issue753_test.go, openapi3/loader.go, openapi3/testdata/issue753.yml
Fix for https://github.com/getkin/kin-openapi/issues/753.
And this PR try to fix https://github.com/getkin/kin-openapi/issues/341, is this desired behavior?
=> openapi3: fix resolving Callbacks

openapi3/loader.go, openapi3/schema.go
=> fixup some coding style divergences

.github/workflows/go.yml, openapi3/issue759_test.go, openapi3/loader.go
=> openapi3: make `bad data ...` error more actionable

openapi3/issue767_test.go, openapi3/schema.go
=> openapi3: fix default values count even when disabled (#767)

.github/docs/openapi3filter.txt, openapi3filter/validation_error_encoder.go
- Need to expose the ConvertErrors func for our service.
- fix failed CI
=> openapi3filter: introduce `func ConvertErrors(err error) error`

openapi3gen/field_info.go, openapi3gen/openapi3gen_test.go
This PR fixes a panic when an embedded type is not a struct. 
To infer the actual type from the embedded type is specifically complex, it is simpler in these cases to use a schema customizer. It makes the most sense to ignore the type.
=> openapi3gen: fix panic when embedded type is not a struct

openapi3filter/issue789_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/validation_test.go
Addresses issue raised here https://github.com/getkin/kin-openapi/issues/789. The fix differs validation to within the schema as the current implemention would always validate incorrectly. I've added test cases for the original issue, along with removing a test within `validation_test.go` which would always fail, so wasn't actually testing the intended behaviour.
=> openapi3filter: fix oneOF validation in query params

openapi3/link.go, openapi3/parameter.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_scheme.go, routers/legacy/router.go
This PR simplifies code by:
- use `!ok` instead of `ok == false`;
- use `strings.TrimSuffix` instead of `strings.HasPrefix` with a condition;
- remove unnecessary `fmt.Sprintf`.
=> openapi3,routers: simplify code

README.md
Projectsveltos depends on _kin-openapi_.
Projectsveltos uses kin-openapi to ensure that the deployed add-ons meet specific constraints defined as openapi policies.
More info on how projectsveltos achieves it can be found here: https://projectsveltos.github.io/sveltos/addon_constraint/
=> Add projectsveltos addon-controller

openapi3/content_test.go, openapi3/discriminator_test.go, openapi3/encoding_test.go, openapi3filter/req_resp_decoder_test.go
This PR refactors tests:
- use `openapi3.BoolPtr` instead of declaring own function in every test;
- use `require.Same` instead of `require.True`;
- use `require.EqualValues` instead of `reflect.DeepEqual`.
=> openapi3: refactor tests: use BoolPtr, require.Same

openapi3/loader_relative_refs_test.go, openapi3/loader_test.go, openapi3/schema_oneOf_test.go, openapi3/schema_test.go, openapi3/validation_options.go, openapi3filter/issue625_test.go, openapi3filter/middleware_test.go, openapi3filter/req_resp_decoder.go, routers/legacy/pathpattern/node.go
This PR corrects spelling mistakes.
=> openapi3,openapi3filter: fix typos in comments, tests

README.md, cmd/validate/main.go
Somewhat fixes #814 
```shell
go run ./cmd/validate --circular=6 --defaults=false --examples=false -- xero_accounting.yaml
```
=> cmd/validate: support setting openapi3.CircularReferenceCounter

openapi3/schema.go, openapi3filter/validation_enum_test.go
Query Parameters are evaluated as int64 vs. a float which is why reflect.DeepEqual fails.
=> Fix Enum Query Parameters 

openapi3/issue819_test.go, openapi3/issue_819_test.go, openapi3/response.go
Implements patterned fields in `openapi3.Responses.Get` 
This seemed to be the quickest fix for #819. Open to other ideas as well!
=> openapi3: support patterned fields in Responses (#819)

openapi3/header.go
in YAML the header has parameter field, but JSON does not.
=> openapi3: fix format error when Header marshal to YAML

openapi3/internalize_refs.go, openapi3/internalize_refs_test.go, openapi3/testdata/issue831/path.yml, openapi3/testdata/issue831/testref.internalizepath.openapi.yml, openapi3/testdata/issue831/testref.internalizepath.openapi.yml.internalized.yml
=> openapi3: fix ref internalization

go.mod
[#836](https://github.com/getkin/kin-openapi/issues/836)
- use of the [sync.Map#CompareAndSwap](https://pkg.go.dev/sync@go1.20#Map.CompareAndSwap) method requires the version of go used to be 1.20
=> fix/ update version of go to 1.20

go.mod, go.sum
This version contains a nil pointer CVE and until the project dependencies (invopop/yaml and stretcher/testify) update their dependencies, we should exclude the vulnerable versions of the gopkg.in/yaml.v3 from the project.
This commit also upgrades the `marshmallow` and `testify` dependency versions because why not?
=> Exclude gopkg.in/yaml.v3 v3.0.0

openapi3/loader_uri_reader.go, openapi3filter/issue639_test.go, openapi3filter/middleware.go, openapi3filter/middleware_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go, openapi3filter/validate_request.go, openapi3filter/validate_response.go, openapi3filter/validate_response_input.go, openapi3filter/validate_set_default_test.go, openapi3filter/validation_error_test.go, openapi3filter/validation_test.go, routers/issue356_test.go
This PR replaces usages of `io/ioutil` with `io` because [io/ioutil](https://pkg.go.dev/io/ioutil) is deprecated:
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
=> Replace deprecated io/ioutil with io

README.md
I fixed example code snippets in the README. Specifically, I replaces `:=` with `=` in the code snippets where compile errors "no new variables on the left side of :=" will be reported.
=> fix compile errors in README example code

openapi3/loader.go
To allow folks who do want to tune the value of the
`CircularReferenceCounter` to do so more easily, we can output the size
of the circular reference in the error message.
=> openapi3: add length of circular reference to error message

openapi2conv/issue847_test.go, openapi2conv/openapi2_conv.go
=> openapi2conv: fix that removes an extra `required` array from `formDataBody`

openapi3/schema.go, openapi3/schema_test.go
Schemas with `XOF` children that allowed for nullable values had their validation broken, as the `null` check happened before the `XOF` check and would fail immediately, without checking if `XOF` allowed for such nullability
=> openapi3: fix schema validation for `anyOf`, `allOf`, `oneOf` operations

openapi3/schema_test.go
cc https://github.com/getkin/kin-openapi/issues/171
=> reproduce incorrect allOf + nullable behaviour

openapi3/issue495_test.go, openapi3/loader.go, openapi3/testdata/draft04.yml
* fixes https://github.com/getkin/kin-openapi/issues/495
* superseeds https://github.com/getkin/kin-openapi/pull/867
Stricto sensu the issue is twofold
1. error message is misleading and hides the actual error
1. schema draft04 deserialization is incorrect in that a `#` ref under `definitions` being dereferenced leads to a "bad data" error, wrongly.
So far only (1) has been addressed.
=>  openapi3: handle refs missing fragment

openapi3filter/issue884_test.go, openapi3filter/validate_request.go
- fix https://github.com/getkin/kin-openapi/issues/884
📝 nested complex structure is not supported with this PR
=> feat: support default value binding with allOfSchema

.github/docs/openapi3.txt, openapi3/schema.go, openapi3/schema_test.go
Only abort further validation if xOf validations were successful AND the value is `nil` (this means that the xOf was nullable for a fact). Otherwise, continue validating against the parent schema
- Closes #890
=> openapi3: fix abort logic of validation for schemas with anyOf, allOf, oneOf

.github/docs/openapi3filter.txt, openapi3filter/req_resp_decoder.go
This makes it easier for a consumer of the library to register a media type that is JSON formatted, such as the many `+json` formats that are available.
Existing tests cover the renamed func.
Fixes #891
=> Make the JSON body decode public

.github/docs/openapi3.txt, maps.sh, openapi3/maplike.go, openapi3/maplike_test.go
=> add Delete operation to maplike structs

.github/docs/openapi3filter.txt, openapi3filter/errors.go, openapi3filter/validate_request_example_test.go
Allows users to perform checks like `errors.Is` which may be returned from the given AuthenticationFunc.
=> openapi3filter: add `Unwrap()` method to SecurityRequirementsError

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
Will try to add missing nested object array items support soon, if you see no issues with the approach taken
Fixes #294
=> openapi3filter: support deepObject with nested objects and array parameters

.github/docs/openapi2.txt, .github/docs/openapi3.txt, openapi2/parameter.go, openapi2conv/openapi2_conv.go, openapi3/issue301_test.go, openapi3/issue341_test.go, openapi3/issue344_test.go, openapi3/issue376_test.go, openapi3/issue495_test.go, openapi3/issue638_test.go, openapi3/issue652_test.go, openapi3/issue689_test.go, openapi3/issue767_test.go, openapi3/load_cicular_ref_with_external_file_test.go, openapi3/load_with_go_embed_test.go, openapi3/loader_issue212_test.go, openapi3/loader_issue220_test.go, openapi3/loader_outside_refs_test.go, openapi3/loader_recursive_ref_test.go, openapi3/loader_relative_refs_test.go, openapi3/loader_test.go, openapi3/refs_test.go, openapi3/schema.go, openapi3/schema_test.go, openapi3/unique_items_checker_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go, openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go, routers/legacy/router_test.go
Resolves https://github.com/getkin/kin-openapi/issues/563
The discussion in issue #563 mentions that this is only supported by openapi2, but the JSON Schema validation spec seems to imply that this should still be supported: https://json-schema.org/draft/2020-12/json-schema-validation#name-type
> If the value of "type" is an array, then an instance validates successfully if its type matches any of the types indicated by the strings in the array.
This PR is a big and breaking change and only really adds two tests. Putting it up for discussion sake. Totally understood if an alternative approach is preferred.
=> openapi2,3: support array of types in `type` field

openapi3/schema.go, openapi3filter/req_resp_decoder.go, openapi3filter/testdata/fixtures/petstore.json, openapi3filter/validation_error_test.go
Previously always returned as `[]string`
=> openapi3filter: fix array of primitives query parameter types

.github/docs/openapi3gen.txt, openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go
=> openapi3gen: allow overriding how a Schema is generated

.github/docs/openapi3.txt, openapi3/paths.go, openapi3/response.go
Support marshaling using [pkg.go.dev/gopkg.in/yaml.v3](https://pkg.go.dev/gopkg.in/yaml.v3)
Related to https://github.com/getkin/kin-openapi/issues/907.
=> openapi3: implement YAML Marshaller interface for paths and responses

.github/docs/openapi3filter.txt, openapi3filter/req_resp_encoder.go
Fixes https://github.com/getkin/kin-openapi/issues/917
=> openapi3filter: guard BodyEncoder registration behind a RW lock

.github/docs/openapi3gen.txt, docs.sh, openapi3gen/internal/subpkg/sub_type.go, openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_newschemarefforvalue_test.go
(Rebase of) Closes https://github.com/getkin/kin-openapi/pull/914
=> openapi3gen: add CreateComponentSchemas option to export object schemas to components

openapi3/schema.go, openapi3/schema_issue940_test.go
https://github.com/getkin/kin-openapi/issues/940
=> openapi3: keep oneOf context in markSchemaErrorKey (#940)

openapi3filter/req_resp_decoder.go
Use String Builder for string concatenation
=> openapi4filter: improve CSV resp decoder performance

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
=> openapi3filter: ensure key matches param name before decoding in `(*urlValuesDecoder) DecodeObject(..)`

.github/docs/openapi3.txt, maps.sh, openapi3/components.go, openapi3/contact.go, openapi3/discriminator.go, openapi3/encoding.go, openapi3/example.go, openapi3/external_docs.go, openapi3/info.go, openapi3/license.go, openapi3/link.go, openapi3/maplike.go, openapi3/media_type.go, openapi3/openapi3.go, openapi3/operation.go, openapi3/parameter.go, openapi3/path_item.go, openapi3/paths.go, openapi3/refs.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_scheme.go, openapi3/server.go, openapi3/tag.go, openapi3/testdata/issue241.yml, openapi3/xml.go, refs.sh
I noticed that some types used `MarshalYAML` as the source of truth for `MarshalJSON`, but others didn't.
Some of those were out of sync, especially with regards to the serialization of extensions.
This PR updates all the `MarshalJSON` functions to call the `MarshalYAML` one, with the result that both JSON and YAML marshalling should result in the same value being written.
=> openapi3: ensure YAML marshalling matches JSON's

openapi2/marsh.go, openapi3/marsh.go
If an error is encountered when attempting to unmarshal an openapi document formatted as JSON, callers will only see the error message from the YAML unmarshal. This adds an error message that combines both.
=> openapi{2,3}: surface both json/yaml unmarshal errors

openapi3/openapi3_test.go
Use https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/require#YAMLEq which is already in use by other test files.
```
[alb@192 kin-openapi]$ git grep -i "yamlEq"
openapi2conv/issue187_test.go:  require.YAMLEq(t, string(spec3), expected)
openapi3/issue883_test.go:              require.YAMLEq(t, `
openapi3/issue883_test.go:              require.YAMLEq(t, spec, string(marshalledYaml))
openapi3/issue883_test.go:              require.YAMLEq(t, `
openapi3/issue883_test.go:              require.YAMLEq(t, `
openapi3/issue883_test.go:              require.YAMLEq(t, spec, string(marshalledYaml))
```
=> openapi3(tests): use testify's `YAMLEq` function

.github/docs/openapi3filter.txt, openapi3filter/middleware.go, openapi3filter/middleware_test.go
This feature modifies the ErrFunc and LogFunc of the validator, just as described in #472 
In contrast to the change described in the issue, this is not a breaking changes, since it adds additional functions to set the LogFunc and the ErrFunc instead of overwriting the existing ones.
=> openapi3filter: add context to Validator Middleware's ErrFunc and LogFunc functions

openapi3/internalize_refs.go, openapi3/internalize_refs_test.go, openapi3/testdata/issue959/components.yml, openapi3/testdata/issue959/openapi.yml, openapi3/testdata/issue959/openapi.yml.internalized.yml
This is an attempt to close #959.
It adapts the code path for `ops.Parameters` to the same logic as the code path for `op.Parameters` (the path parameters), which already uses `derefParameter` to resolve external references in the operations parameters.
Tests as described in the bug ticket are included.
=> openapi3: internalize refs for path parameters

README.md
A mistake in https://github.com/getkin/kin-openapi/pull/945 The new section split it up :(
=> Move paragraph back to its correct section

.github/docs/openapi3.txt, README.md, cmd/validate/main.go, openapi3/issue570_test.go, openapi3/issue615_test.go, openapi3/issue796_test.go, openapi3/load_cicular_ref_with_external_file_test.go, openapi3/loader.go, openapi3/testdata/circularRef/base.yml, openapi3/testdata/circularRef/baz.yml
This PR adds a test scenario that leads to failure of resolving recursive references.
After troubleshooting for a while, I realized that current reference tracking algorithm in not perfect and will always have some edge cases, so I decided to try fixing that for good.
During reference resolution, we keep track of all previous references, and if we find out that the reference is already being resolved, we register a backtracking callback that will assign a pointer to the resolved schema once it's done.
This guarantees that schema will always be resolved regardless of the depth.
=> openapi3: implement circular reference backtracking

openapi3/schema_formats.go, openapi3/schema_formats_test.go
=> openapi3: improve ipv6 validation

openapi3/loader.go, openapi3/loader_circular_test.go, openapi3/testdata/circularRef2/AwsEnvironmentSettings.yaml, openapi3/testdata/circularRef2/circular2.yaml
This PR adds recursive reference handling for single-file references. This prevents infinite recursion.
The test scenario has been kindly provided by @reuvenharrison in #973
Fixes #856
=> openapi3: resolve recursive file references

openapi3/issue82_test.go
This PR adds a test that attempts to reproduce issue #82 without any luck.
I believe the issue can be closed.
Fixes #82
=> openapi3: add a test for additionalProperties: false validation

.github/docs/openapi3.txt, README.md, openapi3/issue735_test.go, openapi3/schema.go, openapi3/schema_formats.go, openapi3/schema_formats_test.go, openapi3/schema_issue492_test.go, openapi3/schema_test.go
This PR adds support for Number and Integer format validators.
Fixes #107
=> openapi3: add support for number and integer format validators

openapi3/loader.go, openapi3/refs.go, openapi3/refs.tmpl
A bug fix for code added in https://github.com/getkin/kin-openapi/pull/955 for a seldom run code path with recursive refs
* The local part was not included when visiting components during recursion
* Also handles the case when base path is null when loading files data in memory
* Copy uri.URL elements to avoid manipulation from outside source
=> openapi3: include local reference parts in refPath saved

openapi2conv/issue979_test.go, openapi2conv/openapi2_conv.go
This PR addresses issue #979. It updates the "type: file" to "type: string" and "format: binary" when converting from V2 to V3 document.
=> fix: update type: file to type: string and format: binary

openapi3/issue499_test.go, openapi3/testdata/issue499/foo.yml, openapi3/testdata/issue499/main.yml
=> test: add a test for #499

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go
See #989 for details, but in a nutshell:
- DecodeArray returns a []any, which means that whenever DecodeArray returns nil, it will actually return a []interface{nil}
- Viewed from decodeStyledParameter, this is an inconsistent behaviour, since decodeStyledParameter returns nil when the query parameters are empty, AND []interface{nil} when there is at least another parameter set.
I am unsure as to whether this is the best way to fix that issue, and am open to suggestions.
Thanks
=> openapi3filter: Remove inconsistency for arrays in queries

openapi3filter/validate_request.go, openapi3filter/validate_request_test.go
This fixes #991, by checking the default value type before applying it.
=> openapi3filter: Fix default arrays application for query parameters

.github/docs/openapi3.txt, openapi3/helpers.go, openapi3/internalize_refs.go
Continuation of https://github.com/getkin/kin-openapi/pull/983
Closes https://github.com/getkin/kin-openapi/issues/994
=> openapi3: export `ComponentRef` for usage in `RefNameResolver`

.github/docs/openapi3.txt, .github/docs/openapi3filter.txt, openapi3/schema.go, openapi3/schema_pattern.go, openapi3/schema_validation_settings.go, openapi3/validation_options.go, openapi3filter/options.go, openapi3filter/validate_request.go
This allows use of a different (more featureful) regex implementation to do validation of fields that have a "pattern" defined.
=> Introduce an option to override the regex implementation

openapi2conv/issue1008_test.go, openapi2conv/openapi2_conv.go
The required fields list of a form was generated by iterating over a map, but in Go maps do not seem to have a natural order.  This causes the list of fields to have some randomness to it.  
Everything else so far is deterministic, and we rely on this to determine if the openapi spec needs to be updated
=> make form required field order deterministic

.github/docs/openapi3.txt, README.md, openapi3/discriminator.go, openapi3/issue495_test.go, openapi3/security_scheme.go, openapi3/stringmap.go
This PR replaces two fields in openapi3 from `map[string]string` by a new type `StringMap`:
- `Discriminator.Mapping`
- `OAuthFlow.Scopes`
This new `StringMap`type will enable unmarshalling of maps with origin in the subsequent PR: https://github.com/getkin/kin-openapi/pull/1007.
=> openapi3: introduce StringMap type to enable unmarshalling of maps with Origin

.github/docs/openapi3.txt, openapi3/example.go, openapi3/origin_test.go, openapi3/testdata/origin/example.yaml, openapi3/testdata/origin/xml.yaml, openapi3/xml.go
This PR adds the `origin` field to two structs that were missed in step 1:
- Example
- XML
In addition, a new unit test demonstrates an edge case that causes a superfluous `origin` key in openapi3.Example.Value when the example is defined as a json object.
=> openapi3: reference originating locations in YAML specs - step 2

.github/docs/openapi3.txt, openapi3/discriminator.go, openapi3/internalize_refs.go, openapi3/internalize_refs_test.go, openapi3/loader.go, openapi3/schema.go, openapi3/security_scheme.go, openapi3/stringmap.go, openapi3/testdata/discriminator.yml, openapi3/testdata/discriminator.yml.internalized.yml, openapi3/testdata/ext.yml
While the type of the discriminator mapping values is a string in the upstream specs, it contains a jsonschema reference to a schema object. It is surprising behaviour that these refs are not handled when calling functions such as InternalizeRefs.
This patch adds the data structures to store the ref internally, and updates the Loader and InternalizeRefs to handle this case. There may be several more functions that need to be updated that I am not aware of.
Since it is not a full Ref object we have to do some fudging to make it work with all the existing ref handling code.
This is a proposal for #1021 , I do not expect it to be the actual implementation.
=> openapi3: process discriminator mapping values as refs

openapi3filter/req_resp_decoder.go
Registers the body decoder out of the box for other JSON content types, e.g. `application/ld+json` and `application/vnd.api+json`. Not as complete as a solution proposed in https://github.com/getkin/kin-openapi/issues/640 but it's an improvement
=> openapi3filter: register decoder for other JSON content types

openapi3/mapping_test.go
This PR consists of a unit test demonstrating a problem with the latest mapping PR: https://github.com/getkin/kin-openapi/pull/1022
The problem is due to the new logic not handling schema names anymore.
The example in the unit test is taken from here: https://spec.openapis.org/oas/v3.0.0#fixed-fields-20
The table in this page states that mapping is "An object to hold mappings between payload values and **schema names** or references."
=> openapi3: fail to load spec because of schema names in mapping 

openapi2conv/issue1016_test.go, openapi2conv/openapi2_conv.go
Fixes Issue: https://github.com/getkin/kin-openapi/issues/1016.
Not sure why additionProperties field is of type openapi3.Schema .Doing a conversion on the ref field
=> openapi2conv: convert schemaRef for additional props

openapi3/server.go
The PR simplifies `Server.MatchRawURL` implementation by replacing `math.Min` with [`min`](https://pkg.go.dev/builtin@go1.22.0).
=> openapi3: simplify by replacing math.Min with min

.github/docs/openapi3.txt, openapi3/schema_formats.go
This PR fixes deprecation comments for `openapi3.DefineStringFormat` and `openapi3.DefineStringFormatCallback`.
According to https://github.com/golang/go/issues/10909#issuecomment-136492606, must be empty line before `// Deprecated: ...`
=> openapi3: fix deprecation comments

openapi2conv/issue187_test.go, openapi3/encoding_test.go, openapi3/issue652_test.go, openapi3/loader_relative_refs_test.go, openapi3/response_issue224_test.go, openapi3filter/validate_request_test.go
This PR fixes the order of parameters in `assert.Equal/require.Equal` statements. According to the [doc](https://pkg.go.dev/github.com/stretchr/testify/require#Equal), the first parameter is `expected`, the second is `actual`.
It is planned [to change the order of assertion arguments](https://github.com/stretchr/testify/issues/1089#Argument_order) to more natural `(actual, expected)` in `v2` of `testify`.
=> test: fix expected-actual parameters in require.Equal

.github/docs/openapi3.txt, openapi3/datetime_schema_test.go, openapi3/schema_formats.go, openapi3/schema_issue492_test.go
Does what it says on the tin, per the permissible value range for `date-month` and `date-mday` of [section 5.6 of the RFC3339 standard](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6)
EDIT TO ADD:
Also updates hours, minutes, and seconds to be bounded from `00-23`, `00-59`, and `00-60` respectively (the `60` is for the leap second).
=> openapi3: update date schema formats to not match months or days of '00'

openapi3/issue82_test.go, openapi3/refs_issue247_test.go, openapi3filter/validate_request.go
The PR replaces `interface{}` with `any` for consistency across the project.
Follows #966
=> openapi3,openapi3filter: replace interface{} with any

.github/docs/openapi3filter.txt, openapi3filter/validate_request.go
The PR refactors `openapi3filter.ValidateRequest`. If `options.MultiError == true`, the function compares `err != nil` twice instead of once.
=> openapi3filter: Simplify ValidateRequest implementation

openapi3filter/issue1045_test.go, openapi3filter/req_resp_decoder.go
this resolves https://github.com/getkin/kin-openapi/issues/1045
=> openapi3filter: validation of `x-www-form-urlencoded` with arbitrary nested allOf

openapi2conv/openapi2_conv.go, openapi2conv/openapi2_conv_test.go
When the schema specified in `additionalProperties` contains another nested schema with `additionalProperties`, the schema references must be converted at all of levels of the nested schemas.
The following examples illustrate the problem.  This pull request fixes the issue by traversing all of the nested schemas in `additionalProperties`, making copies of the objects that are modified by the conversion.
Prior to this change, a schema reference is specified in a top-level `additionalProperties` was being converted correctly.  In the following example OpenAPI 2.0 definition, the reference to "#/definitions/Foo" is correctly converted to "#/components/schemas/Foo" in the OpenAPI 3.0 definition that is produced.
```
{
"basePath": "/v2",
"host": "test.example.com",
"info": {
"title": "MyAPI", …
```
=> openapi2conv: convert references in nested additionalProperties schemas

openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go
Using a SchemaCustomizer, I can't configure schemas for `json.RawMessage` fields. If I have the following struct
```go
type Foo struct {
Bar string `json:"bar"`
Output json.RawMessage `json:"output"`
}
```
The schema customization function will only be called for the Bar field, not the Output field.
=> feat(openapi3gen): Customize json.RawMessage

openapi3gen/openapi3gen.go, openapi3gen/openapi3gen_test.go
openapi3gen generates separate schema component for time.Time properies, when ExportComponentSchemas opt provided.
Here is a small example:
```go
type Some struct {
Name      string
CreatedAt time.Time
}
func main() {
schemas := make(openapi3.Schemas)
g := openapi3gen.NewGenerator(
openapi3gen.UseAllExportedFields(),
openapi3gen.CreateComponentSchemas(openapi3gen.ExportComponentSchemasOptions{
ExportComponentSchemas: true,
}),
)
ref, err := g.NewSchemaRefForValue(&Some{}, schemas)
if err != nil {
panic(err)
}
schema, _ := json.MarshalIndent(ref, "", "  ")
fmt.Println(string(schema))
}
```
Expected output is:
```json
{
"properties": {
"CreatedAt": {
"format": "date-time",
"type": "string"
},
"Name": {
"type": "string"
}
},
"type": "object"
}
```
But for now generator produces following: …
=> openapi3gen: Fix issue with separate component generated for time.Time

openapi3filter/validate_response.go
This PR removes a redundant condition check in the ValidateResponse function.
Currently, there are two checks for `options.ExcludeResponseBody`:
```go
// First check at line 91
if options.ExcludeResponseBody {
// A user turned off validation of a response's body.
return nil
}
// Second check at line 97 (redundant)
if len(content) == 0 || options.ExcludeResponseBody {
// An operation does not contains a validation schema for responses with this status code.
return nil
}
```
The second check is redundant because if `options.ExcludeResponseBody` is true, the function would have already returned at the first check. This PR removes the redundant condition to improve code clarity.
=> openapi3filter: Remove redundant ExcludeResponseBody check

.github/docs/openapi3.txt, go.mod, go.sum, openapi3/callback.go, openapi3/components.go, openapi3/contact.go, openapi3/discriminator.go, openapi3/encoding.go, openapi3/example.go, openapi3/external_docs.go, openapi3/info.go, openapi3/license.go, openapi3/link.go, openapi3/media_type.go, openapi3/operation.go, openapi3/origin.go, openapi3/parameter.go, openapi3/path_item.go, openapi3/paths.go, openapi3/ref.go, openapi3/request_body.go, openapi3/response.go, openapi3/schema.go, openapi3/security_scheme.go, openapi3/server.go, openapi3/tag.go, openapi3/xml.go
The PR is minimizes the chances of YAML files that fail to load with `IncludeOrigin` enabled.
When `IncludeOrigin` is set to true, the loading process adds keys with information about the origin of the YAML objects.
If the original YAML file has a preexisting key with the same name as the key we add, the load will fail.
In order to reduce the likelihood of such failures, I renamed the YAML key we add from `origin` to `__origin__`.
=> openapi3: use __origin__ to minimize collisions

.github/docs/openapi3.txt, openapi3/loader.go, openapi3/origin_test.go, openapi3/stringmap.go
This PR fixes https://github.com/getkin/kin-openapi/issues/1051.
The problem was caused because openapi3 removed `origin` keys from `Schema.Properties` and other map-based types including all `Components` types.
To fix this I changed the behavior to only delete `origin` keys when `IncludeOrigin` is set to true.
Note that this required moving `Loader.IncludeOrigin` to the global scope so that map unmarshalling functions can access it.
For example: `Schemas.UnmarshalJSON` -> `unmarshalStringMapP` -> `popOrigin` which accesses `IncludeOrigin`
=> openapi3: delete origin keys only when IncludeOrigin=true

openapi3/issue376_test.go, openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go, openapi3filter/req_resp_encoder_test.go, openapi3filter/validate_request.go, openapi3filter/validation_error_encoder.go, openapi3filter/validation_error_test.go
`fmt.Sprintf("%v", somthing)` can be safely simplified by `fmt.Sprint(something)`
=> style: Use fmt.Sprint without formating

openapi3filter/issue743_test.go, openapi3filter/validate_request.go
As noted in #743, some users of the `openapi3filter`, largely via
`oapi-codegen` and `openapi.tanna.dev/go/validator`[0] are seeing that
when using an `AuthenticationFunc`, this can lead to errors such as:
request body has an error: value is required but missing
Or:
request body has an error: reading failed: http: invalid Read on closed Body
This turns out to be down to the fact that a call to the
`AuthenticationFunc` may read the request body, but due to the way that
Go's `io.Reader`s can only be read once, this then means the body cannot
be read by anyone else further in the request chain.
To resolve this, we can make sure that each iteration of the
`AuthenticationFunc` gets a fresh copy of the request body (in its own
`io.Reader`).
This follows logic that exists within the …
=> openapi3filter: don't consume request body in `AuthenticatorFunc`

openapi3/loader_uri_reader.go
I am using kin-openapi on a project and Snyk blocked me with an error:
> **Path Traversal**
> Unsanitized input from the request URL flows into os.ReadFile, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to read arbitrary files.
This PR proposes a remediation.
Thank for this really useful library!
=> openapi3: resolve Snyk security warning with path traversal

go.mod, go.sum, openapi3/schema.go, openapi3/schema_test.go
Fixes https://github.com/getkin/kin-openapi/issues/817
Following the suggestion here https://github.com/getkin/kin-openapi/issues/817#issuecomment-1823392667
=> openapi3: replace bigfloat with decimal128 to fix rounding errors during validation

openapi2conv/issue1069_test.go, openapi2conv/openapi2_conv.go
Preserve `externalDocs` on Operations during conversion.
Fixes #1069
- Sets `externalDocs` on operations during v2 → v3 conversion
- Sets `externalDocs` on operations during v3 → v2 conversion
- Adds tests verifying `externalDocs` are preserved at:
- Root level
- Schema level
- Operation level
=> openapi2conv: Preserve externalDocs on operations during conversion

.github/docs/openapi3.txt, openapi3/encoding_test.go, openapi3/helpers.go, openapi3/issue376_test.go, openapi3/issue735_test.go, openapi3/schema.go, openapi3/schema_test.go, openapi3filter/req_resp_decoder_test.go
This adds generic `openapi3.Ptr` function to be used instead of `openapi3.BoolPtr, openapi3.Float64Ptr, openapi3.Int64Ptr, openapi3.Uint64Ptr`.
=> openapi3: use Ptr instead of BoolPtr,Float64Ptr,Int64Ptr,Uint64Ptr

openapi3filter/issue949_test.go, openapi3filter/req_resp_decoder.go
All parts of a multipart/form-data request that are decoded using the PlainBodyDecoder (which is the default for omitted or text/plain parts) are considered to be of type string without these parts being parsed according to their specified schema.
This has been amended and tested in this PR.
This implementation relies on the fact that either an omitted or specified text/plain Content-Type part header will result in a string typed value.
Only parsing of primitive values is supported, as there seems no specifications available for array of object typed parts, as is the case for the different types of supported parameters according to OpenAPI. If this were to change, it should be relatively straightforward to amend the code to make use of an additional implementation of the valueDecoder …
=> openapi3filter: support primitive parsing for individual text like parts in multipart/form-data

openapi3filter/req_resp_decoder.go, openapi3filter/req_resp_decoder_test.go, openapi3filter/validate_response_test.go
Since v0.133.0, empty string values have been incorrectly treated as `nil`. This caused validation to fail for required (non-nullable) parameters that should accept an empty string.
This PR fixes this behavior:
* Empty strings (`""`) are no longer converted to `nil` during parameter decoding.
* Validation for non-nullable parameters now passes correctly when an empty string is provided.
=> openapi3filter: Fix empty string handling in parameter validation
