- openapi3/swagger_loader.go
- openapi3/swagger_loader_test.go
Note: travis says last commit doesn't pass. It does locally though. Maybe some weird caching?
> try resolveSchemaRef on all possible cases

- openapi2conv/openapi2_conv_test.go
- openapi3/operation.go
- openapi3/path_item.go
- openapi3/schema_test.go
- openapi3/server_test.go
- openapi3/swagger_loader.go
- openapi3/swagger_loader_test.go
- openapi3/swagger_test.go
- openapi3filter/validation_test.go
- openapi3gen/openapi3gen_test.go
> yml: YAML support + replace jsontest with require

- openapi3/schema.go
- openapi3/schema_test.go
- openapi3gen/openapi3gen.go
- openapi3gen/openapi3gen_test.go
This PR supports formats strictly.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types
> format: support format

- openapi3/schema.go
- openapi3/schema_test.go
- openapi3filter/validate_request.go
* remove support for multiple types (not in openapi3 at all)
* properly support "nullable"
* some styling & fixes (use IsInt for instance)
* more & better tests
> various fixes

- openapi2conv/openapi2_conv.go
- openapi3/security_scheme.go
- openapi3/security_scheme_test.go
from. https://github.com/getkin/kin-openapi/issues/26
Fix above issue.
I also added a test using OpenAPI3 Sample. c646ac292a8058d4555e3d9096327c51236ab4c8
Also, I found that adding a test erroneously verified each Flow.
Required parameters differ depending on the grant type.
see. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-25
Therefore, I changed the IF of Validate of OAuthFlow, but can not you see whether this policy is good?
> Fix securitySchema.flow is correctly flows and validation

- openapi3/schema_formats.go
> Add missing escape character to regex

- openapi3/response.go
- openapi3/swagger_loader.go
- openapi3/swagger_loader_test.go
Response object should be able to handle header references in Headers field
> Response type fixed to handle header refs

- openapi3/swagger_loader_test.go
I couldn't get `localhost:0` to work.
Fixes #61
> use a much less common server port in tests

- openapi3/discriminator_test.go
> add minimal test case for discriminator

- openapi3filter/param_decoder.go
- openapi3filter/param_decoder_test.go
- openapi3filter/validate_request.go
> Add validation of parameters of all types declared by JSON schema

- README.md
- openapi3filter/req_resp_decoder.go
- openapi3filter/req_resp_decoder_test.go
- openapi3filter/validation_test.go
The title should be self-explanatory
> Fix: MIME type for plain text should be text/plain

- README.md
We use your code to help make writing servers easier. Thanks!
> Add DeepMap's oapi-codegen project to readme

- openapi3filter/req_resp_decoder.go
Fix little nit from PR. Use ParameterInQuery constant instead of
"query".
> Use constant instead of local value

- openapi3/security_scheme.go
- openapi3/security_scheme_test.go
> Fixed validation of empty scopes

- openapi3/schema.go
The schema type here is missing `Title`, so I went ahead and added it.
> Added Title to schema

- go.mod
- jsoninfo/unmarshal_test.go
- openapi3/extension.go
- openapi3/extension_test.go
Addressed https://github.com/getkin/kin-openapi/issues/147
> Fix issue with x-* fields Unmarshal

- go.mod
- go.sum
- jsoninfo/unmarshal_test.go
- openapi3/extension_test.go
- openapi3/schema.go
- openapi3/schema_test.go
- openapi3/swagger_loader.go
- openapi3filter/req_resp_decoder.go
- openapi3filter/validate_request.go
- openapi3filter/validate_request_input.go
- openapi3filter/validation_test.go
Fixes https://github.com/getkin/kin-openapi/issues/151
> apply @pali's fix to issue #151

- openapi3/swagger_loader.go
- openapi3/swagger_loader_relative_refs_test.go
- openapi3filter/router.go
- openapi3filter/router_test.go
- pathpattern/node.go
> Return correct router error when using bad method on existing path

- go.mod
- go.sum
- openapi3/schema.go
- openapi3/schema_test.go
- openapi3filter/router_test.go
Fixes https://github.com/getkin/kin-openapi/issues/168
> Treat nullable as a special case

- openapi3/paths.go
https://github.com/getkin/kin-openapi/issues/174
> removing validation for double slashes

- openapi3filter/req_resp_decoder.go
- openapi3filter/req_resp_decoder_test.go
- openapi3filter/validation_test.go
Fix #106 query param with anyOf failed to parse . Now I have added AnyOf , OneOf and AllOf but haven't Not. because for Not ,i have no idea currently.
> add anyof, allof, oneof in parameter

- openapi3filter/req_resp_decoder.go
- openapi3filter/validation_test.go
> Do not allow decoding not schema as it is not yet supported

- README.md
nothing to say but fixed it :)
> link to github.com/dunglas/vulcain in readme is broken

- openapi3/schema.go
Fixes https://github.com/getkin/kin-openapi/issues/190
The patternProperties field is not supported by OpenAPI 3 Specification as well as it is not compliant with the newest JSON-schema spec.
> Remove patternProperties field support

- openapi3/swagger_loader.go
- openapi3/swagger_loader_test.go
Thanks for a great library, hope this contribution helps! <3
Resolves #24
> Support refs outside #/components - Resolves Issue 24

- openapi3/swagger_loader.go
- openapi3filter/validate_request.go
Fixes https://github.com/getkin/kin-openapi/issues/193
> Validate security requirements sequentially

- openapi2conv/openapi2_conv.go
- openapi2conv/openapi2_conv_test.go
* Params with references are converted correctly
* Global and Path params are converted across
> Fix #156, various parameter issues

- openapi2conv/openapi2_conv.go
- openapi3/swagger_loader.go
- openapi3/swagger_loader_issue212_test.go
Fixes https://github.com/getkin/kin-openapi/issues/212
> handle digits in $ref.s

- openapi3/operation.go
- openapi3/response.go
- openapi3/response_issue224_test.go
- openapi3filter/req_resp_decoder_test.go
- openapi3filter/router_test.go
- openapi3filter/validation_test.go
Fixes https://github.com/getkin/kin-openapi/issues/224
> Responses Object MUST contain at least one response code

- openapi3/info.go
- openapi3/operation.go
- openapi3/operation_test.go
- openapi3/parameter.go
- openapi3/parameter_issue223_test.go
- openapi3/paths.go
- openapi3/response.go
- openapi3/response_issue224_test.go
- openapi3/server.go
- openapi3/server_test.go
- openapi3/swagger.go
- openapi3/swagger_loader_paths_test.go
- openapi3/swagger_loader_test.go
- openapi3/swagger_test.go
- openapi3filter/router_test.go
Fixes https://github.com/getkin/kin-openapi/issues/223
> validate path params against path

- openapi3filter/validation_error_test.go
- openapi3filter/validation_handler.go
Rebased https://github.com/getkin/kin-openapi/pull/219
> Confluentinc middleware

- openapi3/refs_test.go
- openapi3/swagger_loader.go
> handle the main ref dereferencing issues

- openapi2/openapi2.go
- openapi2conv/openapi2_conv.go
- openapi2conv/openapi2_conv_test.go
Added extensions, marshalling/unmarshalling and conversion to and from V3 for:
- Root swagger
- Path 
- Operation
- Parameter (& v3 Requestbody)
- Responses
- SecurityDefinitions
> Swagger2 Extensions

- openapi2conv/openapi2_conv.go
Fixes https://github.com/getkin/kin-openapi/issues/244
> openapi2 security scheme requires accessCode not accesscode

- openapi3/schema.go
- openapi3/schema_validation_settings.go
- openapi3filter/validate_readonly_test.go
- openapi3filter/validate_request.go
- openapi3filter/validate_response.go
> Validator: check readOnly/writeOnly properties

- README.md
Goa v3 depend on kin-openapi
https://github.com/goadesign/goa/blob/v3/go.mod
> feat: add Goa to README

- openapi3filter/req_resp_decoder.go
Add support for content type application/problem+json for response validation
> Add support for application/problem+json

- openapi3/schema.go
- openapi3/schema_test.go
Fixes https://github.com/getkin/kin-openapi/issues/283
> Fix failfast flag handling

- openapi3/server.go
fixes https://github.com/getkin/kin-openapi/issues/299
> support extensions in oasv3.Server

- openapi3/discriminator_test.go
- openapi3/swagger_loader.go
- openapi3/swagger_loader_test.go
- openapi3/testdata/refInRef/messages/definitions.json
- openapi3/testdata/refInRef/messages/request.json
- openapi3/testdata/refInRef/messages/response.json
- openapi3/testdata/refInRef/openapi.json
- openapi3/testdata/testref.openapi.json
- openapi3/testdata/testref.openapi.yml
Fixes https://github.com/getkin/kin-openapi/issues/303
> Enlarge support for JSON Path in $ref resolution

- openapi3/swagger_loader.go
- openapi3/swagger_loader_read_from_uri_func_test.go
Try to fix https://github.com/getkin/kin-openapi/issues/311 and https://github.com/getkin/kin-openapi/issues/231
> Bypass any file/URL reading by ReadFromURIFunc

- openapi3/schema.go
- openapi3filter/validation_discriminator_test.go
Ciao, the change managed to make me validate/parse this spec
```
openapi: 3.0.0
info:
version: 0.2.0
title: yaAPI
paths:
/config:
put:
operationId: ConfigSet
requestBody:
required: true
content:
application/json:
schema:
$ref: '#/components/schemas/config'
responses:
'200':
description: Ok
components:
schemas:
config:
oneOf:
- $ref: '#/components/schemas/simplified'
- $ref: '#/components/schemas/full'
discriminator:
propertyName: conf_type
mapping:
full: '#/components/schemas/full'
simplified: '#/components/schemas/simplified'
generic_config:
type: object
required:
- conf_type
properties:
conf_type:
type: string
enum:
- simplified
- full
discriminator:
propertyName: conf_type
mapping:
full: '#/components/schemas/full'
simplified: '#/components/schemas/simplified'
full:
allOf:
- $ref: …
```
> Adds oneOf/discriminator/mapping management

- openapi3filter/validate_request_test.go
Reproduces #80 
cc #321 
@RiccardoManfrin Could you take a look at this as you've touched discriminator recently please?That'd help a lot :)
> reproduce incorrect discriminator handling with ValidateRequest

- .github/workflows/go.yml
- openapi3/swagger_loader.go
- openapi3/swagger_loader_issue220_test.go
- openapi3/testdata/my-openapi.json
- openapi3/testdata/my-other-openapi.json
cc https://github.com/getkin/kin-openapi/issues/220
> Support loading documents with `filepath.FromSlash`

- openapi3gen/openapi3gen.go
- openapi3gen/openapi3gen_test.go
Didn't open an issue because it was pretty straightforward!
Lemme know if I need to change something, I'm happy to.
> Add uint type to openapi3gen

- routers/gorillamux/router.go
- routers/gorillamux/router_test.go
https://github.com/getkin/kin-openapi/issues/407
> fix issue 407, where if server URL has no path it throws exception

- openapi3/schema.go
- routers/legacy/issue444_test.go
> reproduce + fix #444: ValidateRequest for application/x-yaml

- routers/gorillamux/router.go
- routers/gorillamux/router_test.go
Do not specify a scheme for relative paths.
> Fix issue https://github.com/getkin/kin-openapi/issues/410

- .gitignore
- openapi2/openapi2.go
> Insert produces field

- README.md
- need to import the `openapi3`
- other small fixes
> fix recipe for validating http requests/responses

- openapi2conv/openapi2_conv.go
This change addresses two issues.
* When scopes are present in an openapi3.OAuthFlow the conversion panics
due to an npe because the result.Scopes map had not been initialized.
* The conversion of the flow is incomplete because each oauth2 flow
type has different required fields. The requirements for each type can
be found here https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securityDefinitionsObject
> Fix oauth2 in openapi2conv.FromV3SecurityScheme

- openapi3/loader_test.go
- openapi3/testdata/link-example.yaml
fixes https://github.com/getkin/kin-openapi/issues/44
> test link refs

- openapi3/components.go
> add missing validation of components: examples, links, callbacks

- openapi3/internalize_refs_test.go
- openapi3/testdata/callbacks.yml.internalized.yml
- openapi3/testdata/recursiveRef/openapi.yml.internalized.yml
- openapi3/testdata/spec.yaml.internalized.yml
- openapi3/testdata/testref.openapi.yml.internalized.yml
> Follow up to #540 with more tests

- openapi3filter/req_resp_encoder.go
- openapi3filter/validate_request.go
> following up on #544: do not pass through on unhandled case

- routers/gorillamux/router.go
- routers/gorillamux/router_test.go
fixes https://github.com/getkin/kin-openapi/issues/367
closes https://github.com/getkin/kin-openapi/pull/523
> Handle port number variable of servers given to gorillamux.NewRouter

- README.md
closes https://github.com/getkin/kin-openapi/issues/536
> update README.md with newer router/validator example

- README.md
- openapi3filter/validation_handler.go
> add gitlab.com/jamietanna/httptest-openapi to README.md

- openapi2/openapi2.go
- openapi2conv/issue558_test.go
- openapi2conv/openapi2_conv.go
> fix: add deprecated field to openapi2.Operation

- openapi3/load_cicular_ref_with_external_file_test.go
- openapi3/loader.go
> cleanup after #583

- .github/workflows/go.yml
> upgrade CI tools

- README.md
Fixes https://github.com/getkin/kin-openapi/issues/606
> Add SIMITGROUP`s repo to dependants shortlist

- openapi3/schema.go
- openapi3/schema_test.go
Fixes https://github.com/getkin/kin-openapi/issues/646
> Fix validation of complex enum values

- openapi3filter/req_resp_encoder.go
- openapi3filter/req_resp_encoder_test.go
This is analogous to `RegisterBodyDecoder`
> Add RegisterBodyEncoder

- openapi3/schema.go
- openapi3/schema_formats_test.go
see #674 and TestFormatCallback_WrapError
> fix: wrap the error that came back from the callback (#674)

- openapi3/schema.go
- openapi3/schema_formats_test.go
- openapi3/schema_issue289_test.go
- openapi3filter/issue625_test.go
see #681 and `TestReversePathInMessageSchemaError`.
> fix: error path is lost (#681)

- openapi3filter/issue641_test.go
- openapi3filter/options_test.go
- openapi3filter/req_resp_decoder.go
> fix tests after merge train

- openapi3filter/req_resp_decoder.go
Current openapi3filter code lacks contentType for JSON patch.
> Add json patch support

- openapi3/schema.go
> openapi3: continue validation on valid oneOf properties

- openapi3/schema.go
- openapi3filter/issue733_test.go
- openapi3filter/req_resp_decoder.go
- openapi3filter/req_resp_decoder_test.go
Partial fix for https://github.com/getkin/kin-openapi/issues/733.
> Specify UseNumber() in the JSON decoder during JSON validation

- openapi3/loader_test.go
> openapi3: add test from #731 showing validating doc first is required

- cmd/validate/main.go
> cmd/validate: more expressive errors

- .github/docs/openapi3filter.txt
- README.md
- openapi3filter/options.go
- openapi3filter/validate_request.go
- openapi3filter/validate_response.go
cc  https://github.com/getkin/kin-openapi/issues/781
> openapi3filter: drop useless DefaultOptions

- openapi3/issue794_test.go
- openapi3/loader.go
- openapi3/testdata/issue794.yml
> fix crash on load

- openapi3/encoding_test.go
- openapi3/issue542_test.go
- openapi3/issue615_test.go
This PR fixes tests in `openapi3` package.
> openapi3: fix checks in tests

- cmd/validate/main.go
- openapi3/loader.go
This PR allows us to use tools with pipelines like `swagger-cli bundle -rt yaml openapi.yaml`
> Support loading from stdin

- openapi3/header.go
- openapi3/parameter.go
- openapi3/parameter_issue834_test.go
- openapi3/path_item.go
- routers/gorillamux/router_test.go
- routers/legacy/router_test.go
> openapi3: add missing document parameter validations

- openapi3/loader_outside_refs_test.go
> reproduce issue #423

- openapi3/openapi3.go
- openapi3/openapi3_test.go
open api add server helper functions
- T.Server.RemoveAllServers
- T.Server.AddServers 
simple unit tests for above
> openAPI3 template T class add server helper function

- .github/docs/openapi3.txt
- openapi3/loader.go
- openapi3/loader_test.go
Make Loader testable by allowing it to load a spec from io.Reader.
> Make Loader testable

- README.md
https://github.com/getkin/kin-openapi/compare/v0.123.0...v0.124.0
> openapi3: document v0.124.0 breaking API changes

- .github/docs/openapi3.txt
- maps.sh
- openapi3/info.go
- openapi3/issue972_test.go
- openapi3/loader.go
- openapi3/maplike.go
- openapi3/openapi3.go
- openapi3/schema_formats_test.go
Fixes https://github.com/getkin/kin-openapi/issues/972
> openapi3: allow YAML-marshaling invalid specs

- openapi3/issue961_test.go
- openapi3/testdata/issue961/config_param.yml
- openapi3/testdata/issue961/main.yml
> test: add a test for #961

- openapi3gen/openapi3gen.go
- openapi3gen/openapi3gen_test.go
- openapi3gen/simple_test.go
Fixes https://github.com/getkin/kin-openapi/issues/968
> openapi3gen: generate "nullable: true" for pointers

- openapi3filter/req_resp_decoder.go
Accidentally added in https://github.com/getkin/kin-openapi/pull/990
> openapi3filter: remove double call

- README.md
it looks like a reasonable alternative
> Add github.com/pb33f/libopenapi
